services:
  - type: web
    name: thai-legal-graphrag-api
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: API_HOST
        value: "0.0.0.0"
      - key: API_PORT
        sync: false
      - key: GEMINI_API_KEY
        sync: false